# Server configuration
server.port=8080

# Camel Debug configuration
camel.springboot.jmx-enabled=true
camel.debug.enabled=true
camel.springboot.backlog-tracing=true
camel.debug.standby=true
camel.debug.jmx-connector-enabled=true
camel.debug.jmx-connector-port=1099
camel.debug.break-on-start=false
camel.debug.body-include-streams=true
camel.debug.body-include-files=true

# Hawtio configuration
management.endpoints.web.exposure.include=hawtio,jolokia
hawtio.authenticationEnabled=false
